version: "2"
services:
  pointofdelivery:
    image: openlmis/pointofdelivery
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:9.6-debezium
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/pointofdelivery:/var/log'
